### ISSUE TITLE
Error while running this project on web

### ISSUE THREAD

**Issue by Gbengaol** [EvanBacon/expo-router-twitter#2]
I cloned this project, run `yarn` to install packages, and then run `yarn web` to preview it in the browser. The result of these actions is an error as seen in image below Can you please take a look at this?
<img width="1440" alt="Screenshot 2023-05-20 at 13 41 00" src="https://github.com/EvanBacon/expo-router-twitter/assets/36560069/63565313-26da-4480-9c97-fc2458f6b613">
Node version: v16.17.1

**Comment by sync** [comment]
Native fetch was introduced in Node 18, just tested this project with node 18 and it is all working.

**Comment by Gbengaol** [comment]
I tried with Node 18 and it worked. Thank you
